accelerometer:
  noise_std:
    x: 70.02237071108061
    y: 67.66407897843581
    z: 71.08690782415565
  offset:
    x: 890.74
    y: 484.696
    z: 17641.244
duration_seconds: 10
gyroscope:
  noise_std:
    x: 19.955319065351972
    y: 21.758606481114548
    z: 24.117362293584264
  offset:
    x: -238.921
    y: 276.362
    z: 217.406
timestamp: '2025-11-21T09:03:04.450653'
total_samples: 1000
