imu_madgwick_node:
  ros__parameters:
    use_sim_time: false
    fixed_frame: "odom"
    world_frame: "enu"
    publish_tf: true
    reverse_tf: false
    stateless: false

    constant_dt: 0.01

    use_mag: false
    declination: 0.0      # para evitar crash
    mag_bias_x: 0.0
    mag_bias_y: 0.0
    mag_bias_z: 0.0

    gain: 0.1
    zeta: 0.0

    remove_gravity_vector: false

    orientation_stddev: 0.05

    publish_debug_topics: false

    qos_overrides:
      /parameter_events:
        publisher:
          history: keep_last
          depth: 1
          reliability: reliable
          durability: volatile

      /tf:
        publisher:
          history: keep_last
          depth: 5
          reliability: reliable
          durability: volatile