robot_model:
  name: makerspet_mini
  manufacturer: makerspet.com
  speed:
    mapping: 0.1
    max: 0.2
    min: 0.02
  follow_path:
#   xy_goal_tolerance: 0.0625
    xy_goal_tolerance:
      mapping: 0.05
      max_precision: 0.01
      max_speed: 0.1
    vel_x:
      mapping: 0.1
      max_precision: 0.05
      max_speed: 0.2
