# max_lin_vel = MaxRPM * DerateFactor * WheelDia * PI / 60
# max_ang_vel = max_lin_vel / (wheel_track / 2)
# lin_vel_step = min_lin_vel, obtained from test
# ang_vel_step = min_ang_vel, obtained from test
# max_lin_accel = WheelDia * RatedTorqueKgCm * 100 / WeightKg
# max_ang_accel = max_lin_accel / (wheel_track / 2)
# 200RPM motor, derated 90%
teleop_keyboard_node:
  ros__parameters:
    max_lin_vel: 0.4
    max_ang_vel: 7.72
    lin_vel_step: 0.05
    ang_vel_step: 0.2
    lin_vel_step_large: 0.2
    ang_vel_step_large: 2.5
