controller_manager:
  ros__parameters:
    use_sim_time: false
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    uvrobot_diff_base_controller:
      type: diff_drive_controller/DiffDriveController

uvrobot_diff_base_controller:
  ros__parameters:
    tf_frame_prefix_enable: false
    left_wheel_names: [left_wheel_joint]
    right_wheel_names: [right_wheel_joint]

    #wheel_separation: 0.248
    #wheel_radius: 0.0325

    # parametros scalados
    wheel_separation: 0.7
    wheel_radius: 0.0974

    # For skid drive kinematics it will act as ICR coefficient
    # Kinematic model with ICR coefficient isn't totally accurate and this coefficient can differ
    # for various ground types, but checking on our office floor 1.3 looked approximately alright
    wheel_separation_multiplier: 1.175

    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Feedback from motors is published at around 20 Hz
    publish_rate: 25.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [3.3e-5, 3.3e-5, 0.0, 0.0, 0.0, 2.8e-3] # Values measured experimentally

    # Whether to use feedback or commands for odometry calculations
    open_loop: true

    # Update odometry from velocity
    # in sensor fusion only velocity is used and with this setting it is more accurate
    position_feedback: false
    # velocity computation filtering
    velocity_rolling_window_size: 1

    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false

    # Velocity and acceleration limits
    linear:
      x:
        max_velocity: 1.0 # m/s
        min_velocity: -1.0 # m/s
        max_acceleration: 1.0 # m/s^2
        max_deceleration: -1.0 # m/s^2
        max_acceleration_reverse: -1.0 # m/s^2
        max_deceleration_reverse: 1.0 # m/s^2
        max_jerk: .nan # m/s^3
        min_jerk: .nan # m/s^3

    angular:
      z:
        max_velocity: 3.14 # rad/s
        min_velocity: -3.14 # rad/s
        max_acceleration: 4.0 # rad/s^2
        max_deceleration: -4.0 # rad/s^2
        max_acceleration_reverse: -4.0 # rad/s^2
        max_deceleration_reverse: 4.0 # rad/s^2
        max_jerk: .nan # rad/s^3
        min_jerk: .nan # rad/s^3

